# vim: set ts=2 sw=2 expandtab filetype=yaml
# 
# howto:
# copy _sample_.env to .env en modify according to taste.
# copy _sample_grafana.env to grafana.env en modify according to taste.

version: '3'
services:
  traefik:
    image: traefik:latest
    command: 
      - --web
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "8080"
    networks:
      - dmzhttp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./traefik/acme:/etc/traefik/acme
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik-dashboard"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:traefik.${DNSDOMAIN}"

  influxdb:
    image: influxdb:latest
    networks:
      - databases
    expose:
      - "8086"
    volumes:
      - influxdb_db:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - traefik
    env_file:
      - grafana.env
    networks:
      - dmzhttp
      - databases
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.frontend.rule=Host:grafana.${DNSDOMAIN}"
      - "traefik.docker.network=infra_dmzhttp"
    volumes:
      - grafana_etc:/etc/grafana
      - grafana_lib:/var/lib/grafana
      - grafana_log:/var/log/grafana

  iota2influxdb:
    depends_on:
      - influxdb
    image: goestin/iota2influxdb
    command: "--uri ${IOTA_URIS} --dbhost influxdb"
    networks:
      - databases
      - dmzhttp
    links:
      - iotanode:iotanode

  nextcloud:
    depends_on:
      - traefik
    networks:
      - dmzhttp
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nextcloud"
      - "traefik.frontend.rule=Host:nextcloud.${DNSDOMAIN}"
      - "traefik.docker.network=infra_dmzhttp"
    image: nextcloud
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html



  iotanode:
    depends_on:
      - traefik
    #image: bluedigits/iota-node
    image: berndinox/iota-node
    ports:
      - 0.0.0.0:14625:14625/tcp
      - 0.0.0.0:15600:15600/tcp
    environment:
      - API_PORT=14625
      - TCP_PORT=15600
      - MIN_MEMORY=4G
      - MAX_MEMORY=6G
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.port=14625"
      - "traefik.docker.network=infra_dmzhttp"
      - "traefik.frontend.rule=Host:iota.${DNSDOMAIN}"
      - "traefik.backend=iotanode"
      - "traefik.frontend.entryPoints=https"
    networks:
      - dmzhttp
    volumes:
      - iotadata:/iri/data
      - iotaconf:/iri/conf




networks:
  dmzhttp:
    driver: bridge
  databases:
    driver: bridge


volumes:
  grafana_etc:
  grafana_lib:
  grafana_log:
  influxdb_db:
  nextcloud:
  iotadata:
  iotaconf:
